name: release

on: 
  push:
    tags:
    - 'v*'

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - name: Cache bazel
        uses: actions/cache@v2
        env:
          cache-name: bazel-cache
        with:
          path: | 
            "~/.cache/bazel"
            ~/.cache/bazelisk
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ github.ref }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-

      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build
        run: |
            chmod +x ./release.sh
            ./release.sh
        shell: bash

      - name: Release and Upload Binaries
        run: |
          set -x
          assets=()
          for asset in releases/*; do
            assets+=("-a" "$asset")
          done
          tag_name="${GITHUB_REF##*/}"
          hub release create "${assets[@]}" -m "$tag_name" "$tag_name"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}